environment: dev
last_updated: '2026-07-15T06:00:45Z'
services:
  enrollment:
    version: dev-86f360c8ddaf3b60f61940a2e81e1cd5b1a78454
    digest: simulated-digest-demo
  filemanagement:
    version: dev-86f360c8ddaf3b60f61940a2e81e1cd5b1a78454
    digest: simulated-digest-demo
